[package]
name = "dajarep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version ="4.0.18", features = ["derive"]}
lindera = { version = "0.17.0", features = ["full"] }
regex = "1.6.0"
